- name: Create MySQL NDB template instance
  hosts: mycl
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/mysql_vars.yml
    - vars/deployment_vars.yml
    - vars/aws_template_vars.yml
    - "{{ deployment_log }}"
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: pymysql present
      become: true
      apt:
        name: python3-pymysql
        state: present

#    - name: Add the MySQL/NDB repository
#      import_tasks:
#        file: tasks/mysql_repository.yml

    - name: Install packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-common
        - mysql-cluster-community-client-core
        - mysql-cluster-community-client
        - mysql-cluster-community-server-core
        - mysql-cluster-community-server
        - mysql-cluster-community-data-node
        - mysql-cluster-community-management-server
        - mysql-client
        - mysql-server
        - mysql-shell
        - mysql-router 

    ###>  Check MySQL Data Dir
    - name: Check disk
      become: true
      stat:  
        path: "{{ mysql_data_dir }}"
      register: db_dir

    - debug:
        msg: "{{ db_dir.stat.exists }}"

    - name: Early MySQL check before mount task
      service:
        name: mysql
        state: started
      ignore_errors: true
      register: mysql_details



