--- 
- name: Inital testing for MySQL NDB cluster
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/deployment_output_vars.yml
    - vars/asg_vars
    - vars/aws_template_vars.yml
    - vars/test_vars.yml
  hosts: localhost
  gather_facts: false
  tasks:

    - name: EC2 Assume Role/Profile exists/create
      import_tasks:
        file: tasks/create_assume_role.yml

    - name: AMI Instance exists/create
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        key_name: "{{ key_name }}"
        iam_instance_profile: "{{ instance_profile }}"
        vpc_subnet_id: "{{ subnet_id }}"
        instance_type: "{{ ins_type }}"
        security_groups:
          - "{{ sg }}"
        network:
          assign_public_ip: true
        image_id: "{{ ami_id }}"
        tags:
          environment: "{{ new_env }}"
      register: ec2
    - debug:
        msg: "{{ ec2 }}"

    - name: Register instance in ad-hoc groups
      add_host:
        hostname: "{{ ec2['instances'][0]['network_interfaces'][0]['association']['public_ip'] }}"
        groups:
          - ec2hosts
          - mycl
          - u22
#          - myclmgr

    - name: Update deployment inventory.yml
      shell: |
        php "{{ script_path }}/update_inventory.php" "{{ groups }}"
      ignore_errors: true
      register: php_output
    - debug:
        msg: "{{ php_output }}"

#- name: Run play MySQL NDB Cluster
#  import_playbook: install_mysql_cluster.yml
