- name: Create MySQL NDB template instance
  hosts: mycl
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/mysql_vars.yml
    - vars/deployment_vars.yml
    - vars/aws_template_vars.yml
    - "{{ deployment_log }}"
  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: Apt Cache fresh
      become: true
      apt:
        update_cache: true

    - name: pymysql present
      become: true
      apt:
        name: python3-pymysql
        state: present

    - name: Package rename exists
      become: true
      apt:
        name: rename
        state: present

    - name: Stopping MySQL 
      service:
        name: mysql
        state: stopped
      register: mysql_state
    - debug:
        msg: "{{ mysql_state }}"

    - name: Renaming bin log files
      become: true
      shell: |
        "rename 's/{{ old_bin }}/{{ product_id }}/g' $( ls {{ bin_log_dir }}/*{{ old_bin }}* )"


