---

- name: AWS - rollback deployment infrastructure
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/aws_template_vars.yml
    - vars/deployment_output_vars.yml
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Remove auto scaling group
      amazon.aws.autoscaling_group:
        name: "{{ mycl_asg_name }}"
        availability_zones:  "{{ az }}" 
        region: "{{ region }}"
        launch_template: "{{ k8s_asg_lt }}"
        state: absent
      ignore_errors: true

    - name: Remove launch template
      community.aws.ec2_launch_template:
        state: absent
        launch_template_ids: ["{{ lt_id }}" ]
        name: "{{ myclasg_lt }}"
      ignore_errors: true

    - name: Remove AMI for ASG
      amazon.aws.ec2_ami:
        state: absent
        image_id: "{{ ami_id }}"
        delete_snapshot: true
      ignore_errors: true
      register: ami_info

    - name: Pull product environment instances
      amazon.aws.ec2_instance_info:
        filters: 
          "tag: environment": "{{ new_env }}"
      register: ec2
    - debug:
        msg: ec2

    - name: Remove ec2 instance
      amazon.aws.ec2_instance:
        state: absent
        delete_snapshot: true
        instance_ids: "{{ ec2['instance_ids'][0] }}"
      ignore_errors: true
 
    - name: Remove AWS keypair
      amazon.aws.ec2_key:
        name: "{{ key_name }}"
        state: absent
      register: result
    - debug:
        msg: "{{ result }}"
      ignore_errors: true

    - name: Remove Assume Role
      community.aws.iam_role:
        name: "{{ iam_role }}"
        assume_role_policy_document: "{{ lookup('file','{{ script_path }}/assume_iam_role.json') }}"
        description: "{{ role_desc }}"
        state: absent
        tags:
          environment: "{{ new_env }}"
      ignore_errors: true

    # EC2 instance access
    - name: Remove Instance Profile
      ansible.builtin.command: aws iam delete-instance-profile
        --instance-profile-name "{{ instance_profile }}"
      ignore_errors: true

    - name: Remove IAM Policy 
      amazon.aws.iam_policy:
        iam_type: role
        iam_name: "{{ iam_role }}"
        policy_name: "{{ policy_name }}"
        state: absent
      ignore_errors: true
