- name: Create snapshot configuration "{{ product }}"
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/aws_template_vars.yml
    - vars/deployment_output_vars.yml
  tasks:
- amazon.aws.ec2_snapshot:
    instance_id: "{{ instance_id }}"
    device_name: "{{ device_name }}"
    snapshot_tags:
      frequency: hourly
      source: "{{ mount_point }}"

