- name: MySQL Installation
  hosts: ec2hosts
  remote_user: ubuntu
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/mycl_8.4.2_files.yml

  tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: Test repository downloads
      import_tasks: 
        file: tasks/create_mysql_repository.yml
