- name: MySQL Create Cluster Software Repository
  become: true
  shell: |
    curl "{{ mycl_ndb_web_src }}{{ item }}" | aws s3 cp - "s3://{{ s3_bucket }}/{{ item }}"
  loop: "{{ mycl_ndb_node_files }}"

