  - name: ELB Target Group Exists/Create
    community.aws.elb_target_group:
      name: "{{ elb_target_group }}"
      protocol: tcp
      port: 3306
      target_type: instance
      vpc_id: "{{ vpc_id }}"
      state: present

  - name: ELB for MySQL DB communication exists/create
    amazon.aws.elb_network_lb:
      state: present
      name: "{{ my_elb }}"
      security_group_ids: "{{ sg_info['group_id'] }}"
      subnets: "{{ subnet_info['subnet']['id'] }}"
      listeners:
        - Protocol: TCP
          Port: 3306
          DefaultActions:
            - Type: forward
              TargetGroupName: "{{ elb_target_group }}"
	    
