    - name: Assume Role exists/create
      community.aws.iam_role:
        name: "{{ iam_role }}"
        assume_role_policy_document: "{{ lookup('file','{{ script_path }}/assume_iam_role.json') }}"
        description: "{{ role_desc }}"
        state: present
        tags:
          environment: "{{ new_env }}"
      register: iam_role_info
    - debug:
        msg: "{{ iam_role_info }}"

    - name: Deployment Record Update IAM Role
      lineinfile:
        state: present
        create: true
        path: "{{ deployment_log }}"
        regexp: 'iam_role:'
        line: "iam_role: {{ iam_role_info['role_id'] }}"

    # EC2 instance access
    - name: AWS IAM Instance Profile - Create
      ansible.builtin.command: aws iam create-instance-profile
        --instance-profile-name "{{ instance_profile }}"
      ignore_errors: true

    - name: ECR Policy exists/create
      amazon.aws.iam_policy:
        iam_type: role
        iam_name: "{{ iam_role }}"
        policy_name: "{{ policy_name }}"
        policy_json: "{{ lookup('file', s3_policy ) }}"
        state: present
      register: iam_policy_info
    - debug:
        msg: "{{ iam_policy_info }}"

    - name: Deployment Record Update IAM Policy
      lineinfile:
        state: present
        create: true
        path: "{{ deployment_log }}"
        regexp: 'iam_policy:'
        line: "iam_policy: {{ iam_policy_info['policy_names'][0] }}"

