    - name: Create the ssh group
      become: true
      ansible.builtin.group:
        name: "{{ ssh_group }}"
        state: present

    - name: Create a user with sudo privileges
      become: true
      ansible.builtin.user:
        name: "{{ my_user }}"
        state: present
        groups:
          - sudo
          - adm
          - "{{ ssh_group }}"
        append: true
        create_home: true
        shell: /bin/bash
        password: "{{ lookup('ansible.builtin.env', 'MY_PASS') }}"
        update_password: on_create

    - name: Grant SUDO access
      become: true
      ansible.builtin.shell: |
        echo '{{ my_user }} ALL=(ALL) NOPASSWD:ALL'  >> '/tmp/01-{{ my_user }}-full'
        cp -f '/tmp/01-{{ my_user }}-full'  '/etc/sudoers.d/01-{{ my_user }}-full'

    - name: Set authorized key for remote user
      become: true
      ansible.posix.authorized_key:
        user: "{{ my_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Add ubuntu user to the allowed group
      become: true
      ansible.builtin.shell:
        usermod -a -G "{{ ssh_group }}" ubuntu

